hasol/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
]

main/urls.py
from django.contrib import admin
from django.urls import path, re_path

from main import views

admin.site.site_header = "hasol administration"
app_name = "main"

urlpatterns = [
    path("", views.index, name="index"),
    re_path(r"^rota/(?P<isodate>\d{4}-\d{2}-\d{2})/$", views.rota, name="rota"),
    path("notification/", views.notification, name="notification"),
    path("unsubscribe/", views.unsubscribe, name="unsubscribe"),
    path(
        "unsubscribe/<uuid:key>",
        views.unsubscribe_oneclick,
        name="unsubscribe_oneclick",
    ),
    path("write/", views.write, name="write"),
    path("announce/", views.announce, name="announce"),
    path("todo/", views.todo, name="todo"),
    path("todo/<int:todo_id>/delete/", views.todo_delete, name="todo_delete"),
    path("constitution/", views.constitution, name="constitution"),
    path("garden/", views.garden, name="garden"),
    path("bet/", views.bet, name="bet"),
    path("handbook/", views.handbook, name="handbook"),
]

nutclean/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    include("", include("main.urls")),
]

main/models.py
import uuid

from django.db import models
from django.utils import timezone


class Mate(models.Model):
    name = models.CharField(max_length=300)
    joined_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name


class Job(models.Model):
    title = models.CharField(max_length=300)
    created_at = models.DateTimeField(default=timezone.now)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title


class Assignment(models.Model):
    mate = models.ForeignKey(Mate, null=True, on_delete=models.SET_NULL)
    job = models.ForeignKey(Job, null=True, on_delete=models.SET_NULL)
    week_start = models.DateField(default=timezone.now)

    def __str__(self):
        return (
            self.week_start.isoformat() + ": " + self.mate.name + " – " + self.job.title
        )


class Notification(models.Model):
    email = models.EmailField()
    key = models.UUIDField(default=uuid.uuid4)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.email + " – " + str(self.key)


class NotificationSent(models.Model):
    notification = models.ForeignKey(Notification, on_delete=models.SET_NULL, null=True)
    sent_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.sent_at + " – " + self.notification.email


class Todo(models.Model):
    body = models.CharField(max_length=500)
    created_at = models.DateTimeField(default=timezone.now)
    completed_at = models.DateTimeField(default=None, null=True)

    def __str__(self):
        return self.body

main/forms.py
from django import forms

from main import models


class NotificationForm(forms.ModelForm):
    class Meta:
        model = models.Notification
        fields = ["email"]


class UnsubscribeForm(forms.ModelForm):
    class Meta:
        model = models.Notification
        fields = ["email"]
        labels = {
            "email": "Email to be deleted from notifications",
        }


class UnsubscribeOneclickForm(forms.ModelForm):
    class Meta:
        model = models.Notification
        fields = ["key"]


class TodoForm(forms.ModelForm):
    class Meta:
        model = models.Todo
        fields = ["body"]
        labels = {
            "body": "Add a new to-do item",
        }


class WriteForm(forms.Form):
    body = forms.CharField(widget=forms.Textarea)
    dryrun = forms.BooleanField(required=False)

main/views.py
import json
import uuid
from datetime import datetime, timedelta

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import mail_admins, send_mail
from django.http import HttpResponseForbidden, JsonResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.utils.html import mark_safe
from django.views.decorators.csrf import csrf_exempt

from hasol import settings
from main import forms, models


def index(request):
    # calculate today's week
    now = datetime.now().date()
    monday_this_week = now - timedelta(days=now.weekday())

    # calculate next and previous weeks to the one requested
    previous_monday = monday_this_week - timedelta(days=7)
    next_monday = monday_this_week + timedelta(days=7)

    return render(
        request,
        "main/index.html",
        {
            "assignments": models.Assignment.objects.filter(
                week_start=monday_this_week
            ),
            "is_todays": True,
            "current": monday_this_week,
            "current_endweek": monday_this_week + timedelta(days=6),
            "previous": previous_monday,
            "next": next_monday,
        },
    )


def rota(request, isodate):
    # calculate today's week
    now = datetime.now().date()
    monday_this_week = now - timedelta(days=now.weekday())

    # calculate requested week
    date_requested = datetime.strptime(isodate, "%Y-%m-%d").date()
    monday_that_week = date_requested - timedelta(days=date_requested.weekday())

    # if date is not a Monday, redirect to the Monday of that week
    if date_requested.weekday() != 0:
        return redirect("main:rota", isodate=monday_that_week.date())

    # calculate next and previous weeks to the one requested
    previous_monday = monday_that_week - timedelta(days=7)
    next_monday = monday_that_week + timedelta(days=7)

    return render(
        request,
        "main/index.html",
        {
            "assignments": models.Assignment.objects.filter(
                week_start=monday_that_week
            ),
            "is_todays": monday_this_week == monday_that_week,
            "todays": monday_this_week,
            "current": monday_that_week,
            "current_endweek": monday_that_week + timedelta(days=6),
            "previous": previous_monday,
            "next": next_monday,
        },
    )


def notification(request):
    if request.method == "POST":
        form = forms.NotificationForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get("email")
            if models.Notification.objects.filter(email=email).exists():
                messages.info(request, "This one already exists")
                return redirect("main:notification")
            form.save()
            messages.success(request, "Notification enabled")
            return redirect("main:index")
        else:
            messages.error(request, "Invalid input data")
    else:
        form = forms.NotificationForm()

    return render(request, "main/notification.html", {"form": form})


def unsubscribe(request):
    if request.method == "POST":
        form = forms.UnsubscribeForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get("email")
            notifications = models.Notification.objects.filter(email=email)
            if notifications:
                notifications.delete()
                messages.info(request, "Email notification(s) deleted")
                return redirect("main:unsubscribe")
            else:
                messages.warning(request, "Email does not exist in notifications list")
                return redirect("main:unsubscribe")
        else:
            messages.error(request, "Invalid email")
    else:
        form = forms.UnsubscribeForm()

    return render(request, "main/unsubscribe.html", {"form": form})


def unsubscribe_oneclick(request, key):
    form = forms.UnsubscribeOneclickForm({"key": key})
    if form.is_valid():
        key = form.cleaned_data.get("key")
        notification = models.Notification.objects.filter(key=key)
        if notification:
            notification.delete()
            messages.success(request, "Unsubscribe successful")
        else:
            messages.error(request, "This email is not subscribed")
    else:
        messages.error(request, "Who are you?")

    return redirect("main:unsubscribe")


@login_required
def announce(request):
    if request.method == "POST":
        # hardcoded authentication
        body = request.body.decode("utf-8")
        data = json.loads(body)
        if data.get("key") != "gooHa4o":
            return JsonResponse(status=403, data={})

        # calculate today's week
        now = datetime.now().date()
        monday_this_week = now - timedelta(days=now.weekday())

        # product email content
        this_week_assignments = models.Assignment.objects.filter(
            week_start=monday_this_week
        )
        rota_content = ""
        for a in this_week_assignments:
            rota_content += a.mate.name + " — " + a.job.title + "\n"

        # handle dry run case
        if data.get("dryrun"):
            mail_admins(
                "Nutcroft is clean!",
                render_to_string(
                    "main/rota_announce_email.txt",
                    {
                        "domain": get_current_site(request).domain,
                        "rota": rota_content,
                        "key": uuid.uuid4(),
                    },
                    request=request,
                ),
            )
            return JsonResponse(status=200, data={})

        # sent notifications
        for n in models.Notification.objects.all():
            if n.is_active:
                send_mail(
                    "Nutcroft is clean!",
                    render_to_string(
                        "main/rota_announce_email.txt",
                        {
                            "domain": get_current_site(request).domain,
                            "rota": rota_content,
                            "key": n.key,
                        },
                        request=request,
                    ),
                    settings.DEFAULT_FROM_EMAIL,
                    [n.email],
                )
                models.NotificationSent.objects.create(notification=n)

    return JsonResponse(status=200, data={})


def todo(request):
    todos = models.Todo.objects.filter(completed_at=None)
    done_todos = models.Todo.objects.filter(completed_at__isnull=False).order_by(
        "-completed_at"
    )
    if request.method == "POST":
        form = forms.TodoForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "To do saved.")
            return redirect("main:todo")
        else:
            messages.error(request, "Invalid input data")
    else:
        form = forms.TodoForm()

    return render(
        request,
        "main/todo.html",
        {"form": form, "todos": todos, "done_todos": done_todos},
    )


def todo_delete(request, todo_id):
    if request.method == "POST":
        todo = models.Todo.objects.get(id=todo_id)
        todo.completed_at = datetime.now()
        todo.save()
        return JsonResponse(status=200, data={})


def constitution(request):
    return render(request, "main/constitution.html")


def garden(request):
    return render(request, "main/garden.html")


def handbook(request):
    return render(request, "main/handbook.html")


def bet(request):
    return render(request, "main/bet.html")


@login_required
def write(request):
    if request.method == "POST":
        if not request.user.is_superuser:
            return HttpResponseForbidden()

        form = forms.WriteForm(request.POST)
        if form.is_valid():
            body_content = mark_safe(form.cleaned_data.get("body"))
            dryrun = form.cleaned_data.get("dryrun")

            # calculate today's week
            now = datetime.now().date()
            monday_this_week = now - timedelta(days=now.weekday())

            # product email content
            this_week_assignments = models.Assignment.objects.filter(
                week_start=monday_this_week
            )
            rota_content = ""
            for a in this_week_assignments:
                rota_content += a.mate.name + " — " + a.job.title + "\n"

            # handle dry run case
            if dryrun:
                mail_admins(
                    "Nutcroft is clean!",
                    render_to_string(
                        "main/rota_announce_custom_email.txt",
                        {
                            "domain": get_current_site(request).domain,
                            "body": body_content,
                            "rota": rota_content,
                            "key": uuid.uuid4(),
                        },
                        request=request,
                    ),
                )
                messages.success(request, "Dry run executed")
                return render(request, "main/write.html", {"form": form})

            # sent notifications
            for n in models.Notification.objects.all():
                if n.is_active:
                    send_mail(
                        "Nutcroft is clean!",
                        render_to_string(
                            "main/rota_announce_custom_email.txt",
                            {
                                "domain": get_current_site(request).domain,
                                "body": body_content,
                                "rota": rota_content,
                                "key": n.key,
                            },
                            request=request,
                        ),
                        settings.DEFAULT_FROM_EMAIL,

main/templates/main/bet.html
{% extends 'main/layout.html' %}

{% load static %}

{% block content %}
<section>
    <div class="section-title">
        <a href="{% url 'main:index' %}">Home</a>
    </div>
    <h1>Corona bet — DAY <span id="countup"></span></h1>
    <table>
        <thead>
            <tr>
                <td></td>
                <td>Group</td>
                <td>Primar</td>
                <td>Vulner</td>
                <td>Conct</td>
                <td>Bordr</td>
                <td>Uni</td>
                <td>Restr</td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>N</td>
                <td>60</td>
                <td>120</td>
                <td>365</td>
                <td>250</td>
                <td>90</td>
                <td>60</td>
                <td>60</td>
            </tr>
            <tr>
                <td>Eo</td>
                <td>63</td>
                <td>157</td>
                <td>367</td>
                <td>187</td>
                <td>367</td>
                <td>171</td>
                <td>63</td>
            </tr>
            <tr>
                <td>El</td>
                <td>107</td>
                <td>367</td>
                <td>367</td>
                <td>367</td>
                <td>397</td>
                <td>267</td>
                <td>267</td>
            </tr>
            <tr>
                <td>T</td>
                <td>67</td>
                <td>157</td>
                <td>100</td>
                <td>420</td>
                <td>65</td>
                <td>157</td>
                <td>112</td>
            </tr>
            <tr>
                <td>F</td>
                <td>95</td>
                <td>180</td>
                <td>365</td>
                <td>237</td>
                <td>237</td>
                <td>150</td>
                <td>127</td>
            </tr>
        </tbody>
    </table>

    <p>Numbers are days from the day March 23, 2020, the day UK lockdown started.</p>

    <ol>
        <li>Group: groups of 5 people will be allowed to go out.</li>
        <li>Primar: primary schools will open.</li>
        <li>Vulner: vulnerable people will not be recommended to not go out.</li>
        <li>Conct: concerts of 1000 people will be allowed to take place.</li>
        <li>Bordr: UK borders will open for people to leave.</li>
        <li>Uni: students will be able to physically go to universities.</li>
        <li>Restr: restaurants will open.</li>
    </ol>
</section>
{% endblock %}

{% block scripts %}
<script>
    (function () {
        const ONE_DAY = 24 * 60 * 60 * 1000;  // in milliseconds

        const lockdownStart = new Date(2020, 2, 23);
        const today = new Date();

        const diffDays = Math.ceil((today - lockdownStart) / ONE_DAY);

        document.getElementById('countup').innerText = diffDays;
    })();
</script>
{% endblock %}

main/templates/main/constitution.html
{% extends 'main/layout.html' %}

{% load static %}

{% block content %}
<section>
    <div class="section-title">
        <a href="{% url 'main:index' %}">Home</a>
    </div>
    <h1>Nutcroft Constitution</h1>
    <p>
        If a housemate temporarily departs our esteemed society, they shall be relieved of their cleaning duties.
    </p>
</section>
{% endblock %}

main/templates/main/garden.html
{% extends 'main/layout.html' %}

{% load static %}

{% block content %}
<section>
    <div class="section-title">
        <a href="{% url 'main:index' %}">Home</a>
    </div>
    <h1>Garden</h1>
    <canvas id="garden" width="200" height="500"></canvas>
</section>
{% endblock %}

{% block scripts %}
<script>
    var c = document.getElementById('garden');
    var ctx = c.getContext('2d');
    ctx.font = "11px monospace";

    // the whole
    ctx.fillStyle = 'rgb(200, 200, 200)';
    ctx.fillRect(0, 0, c.width, c.height);

    // garden 3 background
    ctx.fillStyle = 'rgb(200, 0, 0, 0.4)';
    ctx.fillRect(40, 0, 160, 130);
    ctx.stroke();

    // garden 3 tree
    ctx.beginPath();
    ctx.arc(180, 95, 20, 0, 2 * Math.PI);
    ctx.stroke();
    ctx.fillStyle = 'rgb(0, 0, 0, 1)';
    ctx.fillText("TREE", 166, 98);

    // garden 3 raspberries
    ctx.beginPath();
    ctx.arc(160, 45, 5, 0, 2 * Math.PI);
    ctx.stroke();
    ctx.fillStyle = 'rgb(0, 0, 0, 1)';
    ctx.fillText("RASP", 163, 37);

    // garden 2 background
    ctx.fillStyle = 'rgba(0, 0, 200, 0.4)';
    ctx.fillRect(40, 130, 160, 130);

    // garden 2 onion rectangle
    ctx.beginPath();
    ctx.rect(50, 140, 30, 50);
    ctx.stroke();

    // garden 2 onion text
    ctx.save();
    ctx.rotate(-Math.PI/2);
    ctx.fillStyle = 'rgb(0, 0, 0, 1)';
    ctx.fillText("ONION", -180, 67);
    ctx.restore();

    // garden 2 parsley rectangle
    ctx.beginPath();
    ctx.rect(80, 140, 30, 50);
    ctx.stroke();

    // garden 2 parsley text
    ctx.save();
    ctx.rotate(-Math.PI/2);
    ctx.fillStyle = 'rgb(0, 0, 0, 1)';
    ctx.fillText("PARSL", -180, 97);
    ctx.restore();

    // garden 2 compost rect + text
    ctx.beginPath();
    ctx.arc(130, 150, 10, 0, 2 * Math.PI);
    ctx.stroke();
    ctx.fillStyle = 'rgb(0, 0, 0, 1)';
    ctx.fillText("COMP", 120, 175);

    // garden 2 raspberries rectangle
    ctx.beginPath();
    ctx.rect(175, 170, 20, 55);
    ctx.stroke();

    // garden 2 raspberries text
    ctx.save();
    ctx.rotate(-Math.PI/2);
    ctx.fillText("RASPBER", -220, 190);
    ctx.restore();

    // garden 1 background
    ctx.fillStyle = 'rgba(0, 200, 0, 0.4)';
    ctx.fillRect(40, 260, 160, 130);

    // garden 3 some things text
    ctx.fillStyle = 'rgb(0, 0, 0, 1)';
    ctx.fillText("SOME OTHER THINGS", 70, 330);

    // house
    ctx.fillStyle = 'rgba(100, 100, 100, 1)';
    ctx.fillRect(40, 410, 200, 100);
    ctx.fillRect(0, 470, 200, 30);
    ctx.fillStyle = 'rgb(255, 255, 255, 1)';
    ctx.fillText("KAREN", 100, 440);
</script>
{% endblock %}

main/templates/main/handbook.html
{% extends 'main/layout.html' %}

{% load static %}

{% block content %}
<section>
    <div class="section-title">
        <a href="{% url 'main:index' %}">Home</a>
    </div>
    <h1>Nutcroft Handbook</h1>

    <h2>Knives</h2>
    <p>
        Our knives are the most prized possession of our esteemed kitchen. We hold
        them very highly in our modus operandi and there are specific practices that
        one should follow when interacting with them. Namely:
    </p>
    <ol>
        <li>
            Do not use the harsh green side of the sponge because it destroys the
            amazing anti-stick coating of the knives.
        </li>
        <li>
            Do not put the knives into the washing machines because lots of water makes
            them less sharp.
        </li>
        <li>
            Do not put knives with other knives or with other cutlery because it’s like
            a sword fight and they get damaged.
        </li>
        <li>
            Do not place knives inside the washing cutlery rack because it’s made out
            of metal and it will be like a sword fight again.
        </li>
    </ol>
    <p>
        Finally, we are racist towards our knives as all these practices are about
        coloured knives. We don’t care about our generic gold and silver knives.
    </p>
    <p>
        The guardian of the operations around knives is Flo.
    </p>

    <h2>Pans</h2>
    <p>
        We have a wide range of pans, which, in order to take care of, and because they
        are anti-stick pans, we should not use the harsh green side of the sponge on the
        inside side of the pans.
    </p>
    <p>
        In addition, we do not put them inside the dish washing machine (or any washing
        machine actually).
    </p>

    <h2>Cleaning</h2>
    <p>
        We clean our revered house every week and we are very meticulous in keeping it
        clean every time we interact with any room or piece of furniture. We keep our
        cleaning rota at nutcroft.com and one can also subscribe for email updates
        every Monday 8am exactly.
    </p>
    <p>
        The common-for-all weekly house cleaning tasks are:
    </p>
    <ol>
        <li>Kitchen part 1</li>
        <li>Kitchen part 2</li>
        <li>Living room</li>
        <li>Corridors</li>
        <li>Bins</li>
        <li>Vacuum cleaner</li>
        <li>Front porch</li>
    </ol>
    <p>
        In addition to these we also have the toilets which are cleaned by the people
        that share them.
    </p>

    <h2>Bikes</h2>
    <p>
        How could we not have a special relationship with the past, present, and
        future of urban transportation? The best, coolest, most efficient, most
        environmentally friendly, most human friendly, sum positive means of
        transportation is highly regarded in the Nutcroft Foundation. We have resident
        expert bicycle knowledge that we share amongst us, as well as, all the
        necessary tools to fix and maintain one’s bicycle.
    </p>

    <h2>Guests policy</h2>
    <p>
        We welcome all Nutcroft residents to bring their guests, though due to corona
        we have established that one should inform the Foundation beforehand.
    </p>
    <p>
        The process for long term guests (more than 1-2 weeks) is open to discussion.
    </p>

    <h2>Washing machines</h2>
    <p>
        We have a high quality fully automated dish washing machine that we use daily.
        Some things can’t go inside such as the coloured knives and the pans.
    </p>
    <p>
        We also have two clothes washing machines. The one on the ground floor is
        currently facing some issues and may not start if angry. The one in the kitchen
        is super friendly though, starts immediately on the touch of a button.
    </p>

    <h2>Hoover</h2>
    <p>
        We have a state of the art vacuum cleaner which we call Hoover, or just H. The
        official residing place of H is in the living room while H can sometimes be
        found hanging around outside the kitchen.
    </p>
    <p>
        H has many functions and we keep learning new ones as time passes and we
        interact more.
    </p>
    <p>
        H has recently had an illness in which filters  were lost and fans got
        infiltrated by dust. Thankfully we fitted H with new filters as soon as
        possible.
    </p>
    <p>
        The guardian of the Hoover is Karen.
    </p>

    <h2>Garden</h2>
    <p>
        We grow fruit and vegetable in the garden. There is also a newly built fire pit
        which we plan to use in the winter in case the heating breaks down.
    </p>

    <h2>Bins</h2>
    <p>
        We love bins (we have 8 in total) but we are also racist towards them. We have
        4 of them in the kitchen. Namely:
    </p>
    <ul>
        <li>
            Blue: recycling
        </li>
        <li>
            Black: general waste
        </li>
        <li>
            Small brown (small compost): vegan food + crushed egg shells, but not deep
            fried stuff or garlic
        </li>
        <li>
            Big brown: non-vegan food, deep fried food, garlic, non-crushed eggshells
        </li>
    </ul>
    <p>
        For the compost, you can find more information on what is compostable in the
        flyer on the tall fridge.
    </p>
    <p>
        The Southwark Council collects some of our garbage every Thursday. Depending
        on the week it may collect either brown + blue or brown + black. One can find
        the annual schedule on the tall fridge.
    </p>
    <p>
        Every Wednesday night, the resident in charge of bins makes sure that the
        appropriate garbage has been put out and the appropriately coloured bins are
        outside of our front porch.
    </p>
    <p>
        Finally, we have the big compost in the garden, which we put the small
        compost’s contents.
    </p>

    <h2>Alcohol</h2>
    <p>
        How could we be true revolutionaries if we didn’t consume one of the most
        ancient and dangerous substances? Alcohol, and specifically beer and mezcal are
        the two official drinks of the Nutcroft Foundation. While we love those
        timelessly, we continuously try new ones to broaden our horizons.
    </p>

    <h2>Parties</h2>
    <p>
        We hold multi-annual Nutcroft conferences which denote milestones in our
        society’s journey throughout time. Due to corona we had to cut back on those
        but we do have the next one scheduled for July 11th.
    </p>

    <h2>Meetings</h2>
    <p>
        The holy process of Nutcroft is our house meetings. We used to hold them every
        one or two weeks, but due to corona times, we now hold ad-hoc meetings.
    </p>
    <p>
        The meetings take place in the kitchen, sitting around the holy table. Every
        meeting has a moderator and a meeting notes author.
    </p>
    <p>
        The moderator's job is to control who talks so that there is equality amongst
        everybody in talking and hearing time. In order to do this efficiently, and
        without talking, we have adopted some signs to convey our thoughts in a muted
        fasion. Specifically:
    </p>
    <ul>
        <li>
            To convey aggreement, one raises their hands with their palms in a
            spherical shape and shakes them circularly, like
            <a href="https://youtu.be/__R-r2t0vSU?t=112">Helena is doing here</a>.
        </li>
        <li>
            To convey disagreement and respond to a point, one raises their hands with
            their palms in a straight shape, while also holding them parallel to one
            another.
            <a href="https://youtu.be/bNkjHdgV0hg?t=208">Brad shows how here</a>, but
            remember to use both hands (in constrast to Brad).
        </li>
        <li>
            To convey disagreement and respond to a <em>direct</em> point, one uses
            their thumb and index and shapes them like a lobster's claw.
            <a href="https://youtu.be/f48latbh7q4">Here's an example</a> of how it
            should like.
    </ul>
    <p>
        The moderator closely watches everybody and when somebody makes a response,
        they make a mental note and give permission to talk to the person who spoke
        the least, or however else they choose to balance the discussion.
    </p>
    <p>
        The meetings notes author's job is to capture what has been said in the meeting
        so that we can refer to it later. It is a job of utmost importance as the
        meeting notes will be the truth that will help us solidify our decisions.
        Ideally, everybody should read the meeting notes after the meeting and sign
        off on them.
    </p>

    <h2>Mates disagreements</h2>
    <p>
        It is unavoidable to have disagreements between the mates of the house at some
        point. Thus it is important to have a high quality process of solving them.
    </p>
    <p>
        Our process is as follows. The person who has the disagreement talks with the
        person that they disagree with. In case this fails, then the person who has
        the disagreement approaches a third person and all three together try to solve
        the issue at hand. If this process also fails, then the person who has the
        disagreement raises the issue on a house meeting (or asks for one if there
        aren't any scheduled).
    </p>
    <p>
        It is important to externalize our disagreements as the person on the other
        side might not be aware of the issue they might cause, while also it might be
        easier for them to rectify than assumed.
    </p>

    <h2>Consensus</h2>
    <p>
        We try to reach consensus in all the decisions we make. The basis of that is
        a common goal we all share: high quality co-living.
    </p>

</section>
{% endblock %}

main/templates/main/index.html
{% extends 'main/layout.html' %}

{% load static %}

{% block content %}
<nav>
    <div class="nav-left">
        <a href="{% url 'main:rota' next %}">&larr; future</a>
    </div>
    <div class="nav-main">
        <a href="{% url 'main:rota' current %}" class="nav-main-big {% if is_todays %}modifier-currrent{% endif %}">{{ current|date:"M j" }} – {{ current_endweek|date:"M j" }}</a>
    </div>
    <div class="nav-right">
        <a href="{% url 'main:rota' previous %}">past &rarr;</a>
    </div>
</nav>
<main>
    <div class="main-today">
        {% if not is_todays %}
        <a href="{% url 'main:rota' todays %}" class="main-today-small">(go to current week)</a>
        {% endif %}
    </div>
    {% for a in assignments %}
    <div class="main-item">
        <div class="main-item-left">{{ a.mate.name }}</div>
        <div class="main-item-right">{{ a.job.title }}</div>
    </div>
    {% empty %}
    <div class="main-empty">
        No cleaning rota for this week – just dirty.
    </div>
    {% endfor %}
</main>
<footer>
    <a href="{% url 'main:notification' %}">Email notifications</a>
    | <a href="{% url 'main:todo' %}">To-do list</a>
    | <a href="{% url 'main:garden' %}">Garden</a>
    | <a href="{% url 'main:bet' %}">Corona bet</a>
</footer>
{% endblock %}

main/templates/main/write.html
{% extends 'main/layout.html' %}

{% load static %}

{% block content %}
<section>
    <div class="section-title">
        <a href="{% url 'main:index' %}">Home</a>
    </div>
    <h1>Write</h1>
    <form action="{% url 'main:write' %}" method="post">
        {{ form }}
        {% csrf_token %}
        <input type="submit" value="Submit">
    </form>
</section>
{% endblock %}